version: '3'
services:
    deepstream:
        image: deep
        depends_on:
            - redis
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    deepclient:
        image: deepclient
        depends_on:
            - deepstream